image: openjdk:17

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
  steps:
    - step: &lint
        name: Lint
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew ktlintCheck
    - step: &publish
        name: Publish
        services:
          - docker
        caches:
          - gradle
          - gradlewrapper
        script:
          - |
            if grep -Eq "version\s+=\s+\"${BITBUCKET_TAG}-SNAPSHOT\"" ./build.gradle.kts
            then
              echo "Publishing ${BITBUCKET_TAG} version"
              echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
              ./gradlew jib --image="${DOCKER_REGISTRY}/hoenir:${BITBUCKET_TAG}"
            else
              echo "version = \"${BITBUCKET_TAG}-SNAPSHOT\" must exist in build.gradle.kts."
              exit 1
            fi

pipelines:
  default:
    - step: *lint
  tags:
    '**':
      - step: *lint
      - step: *publish
