name: Publish Docker image

on:
  push:
    tags: ['*']

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  docker-publish:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
      - name: Publish Docker image
        run: |
          if ! grep -Eq "version\s+=\s+\"${GITHUB_REF_NAME}-SNAPSHOT\"" ./build.gradle.kts
          then
            echo "version '${GITHUB_REF_NAME}-SNAPSHOT' must exist in the build.gradle.kts make sure app version and tag matches."
            exit 1
          fi
          ./gradlew jib \
            -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }} \
            --image="docker.io/valensas/hoenir:${GITHUB_REF_NAME}"
